apiVersion: v1
kind: Pod
metadata:
  name: banco-de-dados
  labels:
    app: banco-de-dados
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-config
       

